### ISSUE TITLE
Odgovori nisu ispravno generirani (ispisuje se samo latinski naziv)

### ISSUE THREAD

**Issue by HSanel2000** [vdavid033/iooa-2024-kviz#17]
Odgovori nisu ispravno generirani (ispisuje se samo latinski naziv)

**Comment by E-Begich** [comment]
Riješeno, dodana je metoda koja provjerava pitanje po nazivu i sukladno njima ispisuje odgovore. Metoda je pozvana kod ispisa odgovora (u radio buttone).
