### ISSUE TITLE
Middleware: pozvati proizvoljno (random) pitanje, popunjavanje odgovora za to pitanje i odabir točnog (spojiti kviz 4 i 5)

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa-2024-kviz#3]

**Comment by E-Begich** [comment]
Program ispisuje random pitanja. Radi se na tome da ispisuje pitanja a radi se na tome da ispisuje i ispravne latinske nazive i hrvatske nazive.

**Comment by E-Begich** [comment]
Završeno dodavanje ispravnih odgovora sukladno pitanju

**Comment by E-Begich** [comment]
done Hrvoje i Emina
