### ISSUE TITLE
Baza podataka: za odabranu botaničku porodicu (botanical family), izlistati sve biljne vrste (plant species)

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa-2024-kviz#6]

**Comment by vdavid033** [comment]
Napraviti SELECT

**Comment by hcancarev** [comment]
Za izlistati sve biljke iz biljnih vrsta naredba je;  
SELECT * FROM `botanical_family`, `genus` WHERE botanical_family.id=genus.botanical_family_id

**Comment by hcancarev** [comment]
SELECT `botanical_family_id` FROM botanical_family AS BF LEFT JOIN genus AS G ON G.botanical_family_id=BF.id
LEFT JOIN plant_species AS PS ON PS.genus_id=G.id

**Comment by hcancarev** [comment]
> SELECT `botanical_family_id` FROM botanical_family AS BF LEFT JOIN genus AS G ON G.botanical_family_id=BF.id LEFT JOIN plant_species AS PS ON PS.genus_id=G.id

@GizmoStaff  i @DarchyVeleri

**Comment by DarchyVeleri** [comment]
Dodala sam novo koljeno - vaskularne biljke. Prvo sam dodala u botanical family kako bi mogla u genusu pa u plant species. U genus i plant species dodala sam rosa, lilium, tulipa i mimosa.

**Comment by GizmoStaff** [comment]
SELECT p.* FROM `plant_species` AS p
LEFT JOIN genus AS g ON p.genus_id=g.id
LEFT JOIN botanical_family AS bf ON g.botanical_family_id=bf.id
WHERE bf.id=22

**Comment by GizmoStaff** [comment]
> SELECT p.* FROM `plant_species` AS p LEFT JOIN genus AS g ON p.genus_id=g.id LEFT JOIN botanical_family AS bf ON g.botanical_family_id=bf.id WHERE bf.id=22


_ukoliko treba uz biljne vrste vratit i pripadajući id odabrane porodice:_
SELECT p.*, bf.id as botanical_family_id FROM plant_species AS p
LEFT JOIN genus AS g ON p.genus_id=g.id
LEFT JOIN botanical_family AS bf ON g.botanical_family_id=bf.id
WHERE bf.id=22

_ili_

SELECT ps.*, bf.id as botanical_family_id FROM botanical_family as bf, genus as g, plant_species as ps WHERE bf.id=g.botanical_family_id
AND g.id=ps.genus_id
and bf.id=22
