### ISSUE TITLE
Dohvat slika iz baze po id billjne vrste

### ISSUE THREAD

**Issue by E-Begich** [vdavid033/iooa-2024-kviz#7]
Molim vas :)
SELECT image.id, image.image_url FROM image LEFT JOIN plant_species_image ON images.id=plant_species_image.plant_species_id LEFT JOIN plant_species ON plant_species.id=plant_species_image.plant_species_id WHERE plant_species.id=5

**Comment by GizmoStaff** [comment]
_dohvat svih fotografija za određenu biljnu vrstu_
SELECT i.id, i.image_url FROM image i LEFT JOIN plant_species_image psi 
ON i.id=psi.image_id LEFT JOIN plant_species ps ON psi.plant_species_id=ps.id  WHERE ps.id=2

_za dohvat jedne fotografije za određenu biljnu vrstu_
SELECT i.id, i.image_url FROM image i LEFT JOIN plant_species_image psi 
ON i.id=psi.image_id LEFT JOIN plant_species ps ON psi.plant_species_id=ps.id  WHERE ps.id=2
LIMIT 1
